---
# handlers file for estacao
- name: Restart systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved.service
    state: restarted
  become: true

- name: Atualiza dconf
  ansible.builtin.command: dconf update
  become: true

- name: Restart PAM service
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
  become: true

- name: Restart nslcd service
  ansible.builtin.service:
    name: nslcd
    state: restarted
  become: true

- name: Restart cups service
  ansible.builtin.service:
    name: cups
    state: restarted

- name: Restart cups-browsed service
  ansible.builtin.service:
    name: cups-browsed
    state: restarted
