---
# Objetivo: levar a instância ao estado desejado executando a role em teste.
# O Molecule chama este playbook com `molecule converge`.
- name: Converge
  hosts: all
  gather_facts: true # Desative se a role nao depender de facts
  roles:
    - estacao
