---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: estacao
    box: aaronvonawesome/linux-mint-21-cinnamon
    memory: 2048
    cpus: 2
    #   instance_raw_config_args:
    #   - "vm.network 'forwarded_port', guest: 80, host: 8088"
    provider_raw_config_args:
      - gui = true
provisioner:
  name: ansible
  config_options:
      defaults:
        timeout: 60
  inventory:
    links:
      group_vars: ../../../../inventory/group_vars/
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
