---
# defaults file for estacao
estacao_pass_support: "suporte" # type: string username
estacao_pass_root: "root" # type: string password
estacao_pass_vcn: "senha_vcn" # type: string password
estacao_vcnpass64: "senha_vcn" # type: string password
estacao_dtic_network: "1.0.0.0/24" # type: string dns
estacao_serv_ldap: "ldap://0.0.0.0/ ldap://0.0.0.1/"
estacao_ldap_users_dn: "ou=users,dc=example,dc=com"
estacao_ldap_groups_dn: "ou=groups,dc=example,dc=com"
estacao_bind_dn: "cn=binduser,dc=example,dc=com"
estacao_bind_pw: "password"
estacao_nfs_serv: "0.0.0.2:/remote/dir /local/dir nfs timeo=5,retrans=3,retry=10,ro,fg,intr,_netdev,soft,nofail   0   0"
estacao_dtic_gid: "dtic" # type: strign group
estacao_dtic_gidnumber: "9999" # type: string group id
