# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "aaronvonawesome/linux-mint-21-cinnamon"
  # config.vm.box = "aaronvonawesome/linux-mint-20-cinnamon"
  config.vm.provider :virtualbox do |vb|
    # vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
  end
end
