---
# vars file for estacao
google_chrome_recommended:
  HomepageLocation: "http://intranet.cmc.pr.gov.br/"
  RestoreOnStartup: 4
  RestoreOnStartupURLs:
    - "http://intranet.cmc.pr.gov.br/"
  HomepageIsNewTabPage: false
estacao_bookmarks:
  - name: "Câmara Municipal de Curitiba"
    url: "https://www.cmc.pr.gov.br/"
  - name: "Intranet"
    url: "https://intranet.cmc.pr.gov.br/"
  - name: "Correio"
    url: "https://correio.cmc.pr.gov.br/"
  - name: "SPL II"
    url: "https://www.cmc.pr.gov.br/spl/"
  - name: "SPAe"
    url: "https://spae.cmc.pr.gov.br/"
  - name: "Nuvem"
    url: "https://nuvem.cmc.pr.gov.br/"
  - name: "RH-Online"
    url: "https://www.cmc.pr.gov.br/portalrh/"
  - name: "Eloweb Gestão Pública"
    url: "https://acesso.cmcuritiba.eloweb.net/"
  - name: "Almoxarifado"
    url: "https://cmcuritiba.eloweb.net/almoxarifado/"
  - name: "Chamados"
    url: "https://chamados.cmc.pr.gov.br/"
  - name: "Suporte"
    url: "https://chamados.cmc.pr.gov.br/#knowledge_base"
  - name: "Senha"
    url: "https://senha.cmc.pr.gov.br/"
  - name: "APL"
    url: "https://apl.cmc.pr.gov.br/"
  - name: "BIB"
    url: "https://www.cmc.pr.gov.br/bib/"
  - name: "SPA - Legado"
    url: "https://spa.cmc.pr.gov.br/"
  - name: "Cerimonial"
    url: "https://cerimonial.cmc.pr.gov.br/"
  - name: "Minha Biblioteca"
    url: "https://minha-biblioteca.cmc.pr.gov.br/"
  - name: "Registro de frequência"
    url: "https://www.cmc.pr.gov.br/registro-frequencia/"
  - name: "Zoom"
    url: "https://cmc-pr-gov-br.zoom.us/"
  - name: "Rainbow"
    url: "https://web.openrainbow.com/"
  - name: "Prefeitura Municipal de Curitiba"
    url: "https://www.curitiba.pr.gov.br/"
  - name: "SGP"
    children:
      - name: "SGP WEB"
        url: "https://sgpweb.curitiba.pr.gov.br"
      - name: "Consolidação"
        url: "http://172.27.115.72:7070/Consolidacao/pages/login.jsf"
      - name: "Portal Contratos"
        url: "http://portalcontratos.curitiba.pr.gov.br:7070/PortalContratos/portal.do?formAction=init"
      - name: "Solicitações Web"
        url: "http://sgp-web.curitiba.pr.gov.br/sgp/seg/login.do"
      - name: "Consulta Licitações"
        url: "http://consultalicitacao.curitiba.pr.gov.br:9090/ConsultaLicitacoes/"
