---
- name: "Configura usuário suporte : ({{ task_name }})"
  ansible.builtin.user:
    name: suporte
    create_home: true
    state: present
    password: "{{ estacao_pass_support | password_hash('sha512') }}"
    group: users
    append: false
    groups:
      - sudo
  tags:
    - passwords
  register: suporte_user

- name: "Atualizar senha do usuário root : ({{ task_name }})"
  ansible.builtin.user:
    name: root
    password: "{{ estacao_pass_root | password_hash('sha512') }}"
  tags:
    - passwords

- name: "Remover grupo suporte, se existir : ({{ task_name }})"
  ansible.builtin.group:
    name: suporte
    state: absent
