---
# Script para instalar programas adicionais

- name: Altera repositórios para fontes no Brasil
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/official-package-repositories.list
    regexp: "//(packages.linuxmint.com|archive.ubuntu.com)"
    replace: '//br.\1'

- name: Update e Upgrade inicial
  ansible.builtin.apt:
    update_cache: true
    state: latest # noqa: package-latest
    cache_valid_time: 86400

- name: Tira input da instalação do ttf-mscorefonts-installer
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: "msttcorefonts/accepted-mscorefonts-eula"
    vtype: select
    value: "true"

- name: Instala programas
  ansible.builtin.apt:
    name:
      # Acesso remoto
      - rdesktop
      - vino
      - openssh-server
      # Mídia
      - vlc
      - audacity
      - exfat-fuse
      - shotwell
      - gimp
      - gimp-help-pt
      - drawing
      - inkscape
      # Codecs multimida
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-vaapi
      - libavcodec-extra
      - libdvdcss2
      - libdvdnav4
      # Utilitarios e produtividade
      - vim
      - gedit
      - pdfsam
      - unrar
      - ttf-mscorefonts-installer
      # SO
      - ncdu
      - numlockx
      - acct
      - xmlstarlet
      - jq
      - nfs-common
      - libu2f-udev # Microsoft Edge
    state: present

- name: Instala o Chrome, pq chrome é especial
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present

- name: Instala o Microsoft Edge
  ansible.builtin.apt:
    deb: "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_124.0.2478.51-1_amd64.deb"
    state: present
  register: ret
  failed_when: >
    (ret.failed) and
    ("A later version is already installed" not in ret.msg)

# - name: Debug edge
#   ansible.builtin.debug:
#     var: ret

- name: "Verifica se Microsoft Edge esta na versao mais recente"
  ansible.builtin.apt:
    name: microsoft-edge-stable
    state: latest
    only_upgrade: true

- name: "Create mimeapps.list file with the specified content"
  ansible.builtin.copy:
    dest: /etc/skel/.config/mimeapps.list
    mode: "0644"
    src: "mimeapps.list"
