---
# Script para instalar programas adicionais

- name: Altera repositório Ubuntu para fonte no Brasil
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/official-package-repositories.list
    regexp: "//(archive.ubuntu.com)"
    replace: '//br.\1'

- name: Altera repositório linuxmint para fonte no Brasil
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/official-package-repositories.list
    regexp: "//packages.linuxmint.com"
    replace: "//mint-packages.c3sl.ufpr.br"

- name: Update e Upgrade inicial
  ansible.builtin.apt:
    update_cache: true
    state: latest # noqa: package-latest
    # não usar cache_valid_time aqui para forçar atualização do repo

- name: Tira input da instalação do ttf-mscorefonts-installer
  ansible.builtin.debconf:
    name: ttf-mscorefonts-installer
    question: "msttcorefonts/accepted-mscorefonts-eula"
    vtype: select
    value: "true"

- name: Instala programas via apt package manager
  ansible.builtin.apt:
    name:
      # Acesso remoto (VNC, RDP, SSH)
      - x11vnc
      - xrdp
      - xorgxrdp
      - openssh-server
      - zenity
      # Mídia
      - vlc
      - audacity
      - exfat-fuse
      - shotwell
      - gimp
      - gimp-help-pt
      - drawing
      - inkscape
      # Codecs multimida
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-vaapi
      - libavcodec-extra
      - libdvdcss2
      - libdvdnav4
      # Utilitarios e produtividade
      - vim
      - gedit
      - unrar
      - ttf-mscorefonts-installer
      # SO
      - linux-oem-24.04 # driver de vídeo
      - ncdu
      - numlockx
      - acct
      - xmlstarlet
      - jq
      - nfs-common
      - libu2f-udev # Microsoft Edge
      - s3fs
    state: present

- name: Remove pdfsam antigo (conflitante com pdfsam-basic)
  become: true
  ansible.builtin.apt:
    name: pdfsam
    state: absent
    purge: true

- name: Instala o PDFSam Basic via .deb oficial
  become: true
  ansible.builtin.apt:
    deb: https://github.com/torakiki/pdfsam/releases/download/v5.4.5/pdfsam-basic_5.4.5-1_amd64.deb
    state: present
  register: ret_pdfsam
  failed_when: >
    (ret_pdfsam.failed) and
    ("A later version is already installed" not in ret_pdfsam.msg)

- name: Instala o Chrome, pq chrome é especial
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present

# A versão do Edge no repositório da Microsoft pode não ser a mais recente, por isso instalamos via .deb primeiro e depois atualizamos

- name: Instala o Microsoft Edge
  ansible.builtin.apt:
    deb: https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_143.0.3650.139-1_amd64.deb
    state: present
  register: ret
  failed_when: >
    (ret.failed) and
    ("A later version is already installed" not in ret.msg)

# - name: Debug do edge
#   ansible.builtin.debug:
#     var: ret

- name: Verifica se Microsoft Edge esta na versao mais recente
  ansible.builtin.apt:
    name: microsoft-edge-stable
    state: latest
    only_upgrade: true
