#035
- name: Copia imagem para o icone de suporte no desktop
  ansible.builtin.copy:
    src: ../arquivos/imagens/suporte_tux.png 
    dest: /usr/share/pixmaps/

- name: chmod 644 suporte_tux
  ansible.builtin.file:
    path: /usr/share/pixmaps/suporte_tux.png
    mode: '0644'

- name: Copia imagem para o icone do mensageiro
  ansible.builtin.copy:
    src: ../arquivos/imagens/Rainbow.png
    dest: /usr/share/pixmaps/

- name: chmod 644 rainbow
  ansible.builtin.file:
    path: /usr/share/pixmaps/Rainbow.png
    mode: '0644'

- name: mkdir
  ansible.builtin.file:
    path: /usr/share/backgrounds/cmc
    state: directory

- name: Copia imagem de background para a pasta adequada
  ansible.builtin.copy:
    src: ../arquivos/imagens/desktop-bg.png
    dest: /usr/share/backgrounds/cmc/

- name: chmod 644 desktop
  ansible.builtin.file:
    path: /usr/share/backgrounds/cmc/desktop-bg.png
    mode: '0644'

- name: Copia imagem de background do greeter para pasta adequada
  ansible.builtin.copy:
    src: ../arquivos/imagens/login-bg.jpg
    dest: /usr/share/backgrounds/cmc/

- name: chmod 644 login-bg
  ansible.builtin.file:
    path: /usr/share/backgrounds/cmc/login-bg.jpg
    mode: '0644'
