---
# 040-skel

- name: Cria os diretórios padrões
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  with_items:
    - path: /etc/skel/Desktop
    - path: /etc/skel/Downloads
    - path: /etc/skel/Nuvem
    - path: /etc/skel/.config/autostart
    - path: /etc/skel/.gimp-2.10
    - path: /home/Docs.Locais
      owner: nobody
      group: nogroup
      mode: 1777
  become: true

- name: Cria o link simbólico /etc/skel/Docs.Locais apontando para /home/Docs.Locais
  ansible.builtin.file:
    path: /etc/skel/Docs.Locais
    src: /home/Docs.Locais
    state: link
  become: true

- name: Cria arquivo padrão user-dirs.dirs
  ansible.builtin.copy:
    dest: /etc/skel/.config/user-dirs.dirs
    content: |
      XDG_DESKTOP_DIR="$HOME/Desktop"
      XDG_DOCUMENTS_DIR="$HOME/Docs.Locais"
      XDG_DOWNLOAD_DIR="$HOME/Downloads"
    mode: "0644"

- name: Cria o arquivo user-dirs.locale com conteúdo "pt_BR"
  ansible.builtin.copy:
    content: "pt_BR"
    dest: /etc/skel/.config/user-dirs.locale
    mode: "0644"

# Desabilita a atualização automatica dos user-dirs no XDG
- name: Modifica o arquivo user-dirs.conf
  ansible.builtin.lineinfile:
    path: /etc/xdg/user-dirs.conf
    regexp: "^enabled="
    line: "enabled=False"

# Cria icones de suporte, firefox, chrome
- name: Cria atalhos padrões no desktop
  ansible.builtin.copy:
    dest: "/etc/skel/Desktop/{{ item }}.desktop"
    remote_src: false
    src: "atalhos/{{ item }}.desktop"
    mode: "+x"
  with_items:
    - Firefox
    - google-chrome
    - Suporte
    - Rainbow

- name: Configura o arquivo de sessão do GIMP
  ansible.builtin.copy:
    dest: "/etc/skel/.gimp-2.10/sessionrc"
    remote_src: false
    src: "gimp_sessionrc"
    mode: "0644"

- name: Cria política de privacidade
  ansible.builtin.copy:
    dest: "/etc/skel/.politicainformatica.sh"
    remote_src: false
    src: ".politicainformatica.sh"
    mode: "0644"

# Pode dar problema se ja tiver esse bloco e ele não tiver os markers
# do ansible. TODO: Achar uma forma de evitar isso
- name: Aplica política de privacidade
  ansible.builtin.blockinfile:
    path: "/etc/skel/.profile"
    marker: '# {mark} ANSIBLE MANEGED BLOCK Politica de Privacidade'
    block: |
      if [ -f "$HOME/.politicainformatica.sh" ]; then
        bash $HOME/.politicainformatica.sh;
      fi
