# 040-skel

# Cria os diretorios padrões
- name: mkdir Desktop
  ansible.builtin.file:
    path: /etc/skel/Desktop
    state: directory

- name: mkdir Downloads
  ansible.builtin.file:
    path: /etc/skel/Downloads
    state: directory

- name: mkdir Nuvem
  ansible.builtin.file:
    path: /etc/skel/Nuvem
    state: directory

- name: mkdir autostart
  ansible.builtin.file:
    path: /etc/skel/.config/autostart
    state: directory
    
- name: mkdir Docs.Locais
  ansible.builtin.file:
    path: /home/Docs.Locais
    state: directory

- name: Create a symbolic link (ln -sf)
  ansible.builtin.file:
    src: /home/Docs.Locais
    dest: /etc/skel/Docs.Locais
    owner: foo
    group: foo
    state: link
    
# Cria o arquivo padrão de user-dirs.dirs
- name: Cria o arquivo padrão de user-dirs.dirs
  copy:
    content: |
          XDG_DESKTOP_DIR="{{ ansible_env.HOME }}/Desktop"
          XDG_DOCUMENTS_DIR="{{ ansible_env.HOME }}/Docs.Locais"
          XDG_DOWNLOAD_DIR="{{ ansible_env.HOME }}/Downloads"
    dest: /etc/skel/.config/user-dirs.dirs

# Cria o arquivo padrão de local
- name: Cria o arquivo padrão de local
  copy:
    content: "pt_BR"
    dest: "/etc/skel/.config/user-dirs.locale"

# Desabilita a atualização automatica dos user-dirs no XDG
- name: Desabilita a atualização automática dos user-dirs no XDG
  lineinfile:
    path: "/etc/xdg/user-dirs.conf"
    line: "enabled=False"
    regexp: "enabled=True"
    state: present

# Atualiza permissões dos Docs.Locais
- name: Atualiza permissões dos Docs.Locais
  file:
    path: "/home/Docs.Locais"
    owner: nobody
    group: nogroup
    mode: "1777"
    state: directory

# Cria icones de suporte, firefox, chrome
- name: Cria ícones de suporte, Firefox e Chrome
  blockinfile:
    path: "/etc/skel/Desktop/Firefox.desktop"
    content: |
      #!/usr/bin/env xdg-open
      [Desktop Entry]
      Version=1.0
      Type=Application
      Terminal=false
      Name=Firefox
      Exec=firefox
      Icon[pt_BR]=firefox
      Name[pt_BR]=Firefox
      Icon=firefox

# Configura atalho para o mensageiro
# O icone é configurado no script 035
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Firefox.desktop
      copy:
        dest: /etc/skel/Desktop/Firefox.desktop
        content: |
          #!/usr/bin/env xdg-open
          [Desktop Entry]
          Version=1.0
          Type=Application
          Terminal=false
          Name=Firefox
          Exec=firefox
          Icon[pt_BR]=firefox
          Name[pt_BR]=Firefox
          Icon=firefox

    - name: Create google-chrome.desktop
      copy:
        dest: /etc/skel/Desktop/google-chrome.desktop
        content: |
          #!/usr/bin/env xdg-open
          [Desktop Entry]
          Version=1.0
          Name=Google Chrome
          GenericName[pt_BR]=Navegador da Internet
          GenericName=Web Browser
          Comment=Access the Internet
          Comment[pt_BR]=Acessar a internet
          Exec=/usr/bin/google-chrome-stable %U
          StartupNotify=true
          Terminal=false
          Icon=google-chrome
          Type=Application
          Categories=Network;WebBrowser;
          MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
          Actions=new-window;new-private-window;

          [Desktop Action new-window]
          Name=New Window
          Name[pt_BR]=Nova janela
          Exec=/usr/bin/google-chrome-stable

          [Desktop Action new-private-window]
          Name=New Incognito Window
          Name[pt_BR]=Nova janela anônima
          Exec=/usr/bin/google-chrome-stable --incognito

    - name: Create Suporte.desktop
      copy:
        dest: /etc/skel/Desktop/Suporte.desktop
        content: |
          #!/usr/bin/env xdg-open
          [Desktop Entry]
          Version=1.0
          Type=Application
          Terminal=false
          Name=Suporte
          Exec=firefox suporte.cmc.pr.gov.br
          Icon[pt_BR]=firefox
          Name[pt_BR]=Suporte
          Icon=/usr/share/pixmaps/suporte_tux.png

# Ajusta permissões dos launchers
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Make sure the .desktop files are executable
      file:
        path: /etc/skel/Desktop/*.desktop
        mode: '+x'
      become: yes
      become_method: sudo

    - name: Create .gimp-2.10 directory
      file:
        path: /etc/skel/.gimp-2.10/
        state: directory
      become: yes
      become_method: sudo

# Configuração padrão do GIMP
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create GIMP sessionrc file
      copy:
        dest: /etc/skel/.gimp-2.10/sessionrc
        content: |
          # GIMP sessionrc
          (session-info "toplevel"
              (factory-entry "gimp-empty-image-window")
              (position 184 193)
              (size 620 200)
              (open-on-exit))
          (session-info "toplevel"
              (factory-entry "gimp-single-image-window")
              (position 0 30)
              (size 1022 672)
              (open-on-exit)
              (aux-info
                  (left-docks-width "120")
                  (right-docks-position "690"))
              (gimp-toolbox
                  (side left)
                  (book
                      (current-page 0)
                      (dockable "gimp-tool-options"
                          (tab-style automatic))))
              (gimp-dock
                  (side right)
                  (book
                      (current-page 0)
                      (dockable "gimp-layer-list"
                          (tab-style automatic)
                          (preview-size 32))
                      (dockable "gimp-channel-list"
                          (tab-style automatic)
                          (preview-size 32))
                      (dockable "gimp-vectors-list"
                          (tab-style automatic)
                          (preview-size 32))
                      (dockable "gimp-undo-history"
                          (tab-style automatic)))
                  (book
                      (position 394)
                      (current-page 0)
                      (dockable "gimp-brush-grid"
                          (tab-style automatic))
                      (dockable "gimp-pattern-grid"
                          (tab-style automatic))
                      (dockable "gimp-gradient-list"
                          (tab-style automatic)))))

          (hide-docks no)
          (single-window-mode yes)
          (last-tip-shown 0)

          # end of sessionrc
      become: yes
      become_method: sudo

# Política de privacidade
# ???

# Forçar logout se não aceitar política de privacidade
- name: Configurar política de informática no .profile
  tasks:
    - name: Verificar se a linha já existe no .profile
      shell: "grep -q 'bash $HOME/.politicainformatica.sh;' /etc/skel/.profile"
      register: grep_result
      changed_when: false
      check_mode: no

    - name: Adicionar linhas ao .profile
      blockinfile:
        path: /etc/skel/.profile
        block: |
          if [ -f "$HOME/.politicainformatica.sh" ]; then
            bash $HOME/.politicainformatica.sh;
          fi
      when: grep_result.rc != 0



