---
- name: "Copiar ícones para /usr/share/pixmaps/ : ({{ task_name }})"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/pixmaps/
    mode: "0644"
  loop:
    # - imagens/Rainbow.png
    - imagens/suporte_tux.png

- name: "Copiar imagens de background para /usr/share/backgrounds/cmc/ : ({{ task_name }})"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/cmc/
    mode: "0644"
  loop:
    - imagens/login-bg.jpg
    - imagens/desktop-bg.png
