---
- name: Cria os diretórios padrão
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/skel/Desktop
    - /etc/skel/Downloads
    - /etc/skel/Música
    - /etc/skel/Imagens
    - /etc/skel/Vídeos

- name: Garante que Docs.Locais está sem arquivos
  ansible.builtin.file:
    path: /home/Docs.Locais
    state: absent

- name: Cria Docs.Locais
  ansible.builtin.file:
    path: /home/Docs.Locais
    state: directory
    mode: "1777"
    owner: nobody
    group: nogroup

- name: Cria o link simbólico para Docs.Locais
  ansible.builtin.file:
    path: /etc/skel/Docs.Locais
    src: /home/Docs.Locais
    state: link

- name: "Cria arquivo padrão user-dirs.dirs"
  ansible.builtin.copy:
    dest: /etc/skel/.config/user-dirs.dirs
    content: |
      XDG_DESKTOP_DIR=\"\$HOME/Desktop\"
      XDG_DOWNLOAD_DIR=\"\$HOME/Downloads\"
      XDG_DOCUMENTS_DIR=\"\$HOME/Docs.Locais\"
      XDG_MUSIC_DIR=\"\$HOME/Música\"
      XDG_PICTURES_DIR=\"\$HOME/Imagens\"
      XDG_VIDEOS_DIR=\"\$HOME/Vídeos\
    mode: "0644"

- name: "Cria o arquivo user-dirs.locale com conteúdo 'pt_BR'"
  ansible.builtin.copy:
    content: "pt_BR"
    dest: /etc/skel/.config/user-dirs.locale
    mode: "0644"

- name: Desabilita a atualização automatica dos user-dirs no XDG
  ansible.builtin.lineinfile:
    path: /etc/xdg/user-dirs.conf
    regexp: "^enabled=True"
    line: "enabled=False"

- name: Cria icones de Firefox e Chrome
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "+x"
    remote_src: true
  loop:
    - {
        src: "/usr/share/applications/firefox.desktop",
        dest: "/etc/skel/Desktop/firefox.desktop",
      }
    - {
        src: "/usr/share/applications/google-chrome.desktop",
        dest: "/etc/skel/Desktop/google-chrome.desktop",
      }

- name: Cria icone de Suporte
  ansible.builtin.copy:
    src: atalhos/Suporte.desktop
    dest: /etc/skel/Desktop/Suporte.desktop
    owner: root
    group: root
    mode: "+x"

- name: "Cria política de privacidade"
  ansible.builtin.template:
    src: "politicainformatica.sh.j2"
    dest: "/etc/skel/.politicainformatica.sh"
    owner: root
    group: root
    mode: "0755"

- name: "Força logout se nao aceitar a politica de privacidade"
  ansible.builtin.lineinfile:
    path: /etc/skel/.profile
    insertafter: EOF
    line: |
      if [ -f "$HOME/.politicainformatica.sh" ]; then
        bash $HOME/.politicainformatica.sh;
      fi
    create: true
    state: present
    backrefs: true
    regexp: 'bash \$HOME\/\.politicainformatica\.sh;'
    mode: "0644"
