---
- name: "Configura firefox"
  ansible.builtin.copy:
    dest: "/usr/lib/firefox/{{ item.dest }}"
    src: "{{ item.src }}"
    mode: "0644"
  loop:
    - dest: "defaults/pref/local-settings.js"
      src: "firefox-config.1"
    - dest: "mozilla.cfg"
      src: "firefox-config.2"
    - dest: "browser/override.ini"
      src: "firefox-config.3"

- name: "Cria pastas de configuração do Chrome"
  ansible.builtin.file:
    state: directory
    path: "/etc/opt/chrome/policies/{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop:
    - recommended
    - managed

- name: "Configura Google Chrome"
  ansible.builtin.copy:
    dest: "/etc/opt/chrome/policies/recommended/cmc.json"
    src: "chrome-config"
    owner: root
    group: root
    mode: "0644"

- name: "Gera bookmarks dos navegadores"
  ansible.builtin.template:
    dest: "{{ item.bookmarks_config_file }}"
    src: "templates/bookmarks_{{ item.browser }}.j2"
    lstrip_blocks: true
    mode: "0644"
  loop:
    - browser: "firefox"
      bookmarks_config_file: "/usr/lib/firefox/distribution/policies.json"
    - browser: google-chrome
      bookmarks_config_file: "/etc/opt/chrome/policies/managed/cmc.json"
