---
# 070-politica-informatica

- name: Criar diretório /usr/local/cmc/scripts
  ansible.builtin.file:
    path: /usr/local/cmc/scripts
    state: directory
    mode: "0755"

- name: Criar o script forcelogout.sh
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      if [ -f "$HOME/.forcelogout" ]; then
          rm "$HOME/.forcelogout";
          pkill -9 -u "$USER"
      fi
    dest: /usr/local/cmc/scripts/forcelogout.sh
    mode: "0755"

- name: Copiar o arquivo politica-informatica.txt
  ansible.builtin.copy:
    src: politica-informatica.txt
    dest: /usr/local/cmc/politica-informatica.txt
