# 080-desabilita-tty

# Desabilita a troca de terminals com CTRL + ALT + Fx
- name: Configurar xorg.conf para desabilitar troca de terminais
  tasks:
    - name: Criar o arquivo /etc/X11/xorg.conf se não existir
      file:
        path: /etc/X11/xorg.conf
        state: touch
      check_mode: no

    - name: Verificar se a opção DontVTSwitch já existe no arquivo
      shell: "grep -q 'Option \"DontVTSwitch\" \"true\"' /etc/X11/xorg.conf"
      register: grep_result
      changed_when: false
      check_mode: no

    - name: Adicionar configuração no arquivo xorg.conf
      blockinfile:
        path: /etc/X11/xorg.conf
        block: |
          Section "ServerFlags"
              Option "DontVTSwitch" "true"
          EndSection
      when: grep_result.rc != 0
