#100-dconf

# Cria os diretórios de configuração
- name: mkdir profile
  ansible.builtin.file:
    path: /etc/dconf/profile
    state: directory

- name: mkdir local.d
  ansible.builtin.file:
    path: /etc/dconf/db/local.d/
    state: directory

# Seta o local do arquivo de config (local, ou seja, ficará em /db/local.d)
- name: Criar arquivo de configuração dconf para o usuário
  tasks:
    - name: Criar arquivo de configuração dconf
      copy:
        content: |
          user-db:user
          system-db:local
        dest: /etc/dconf/profile/user


# Senha login remoto
- name: Definir variável VNCPASS64
  vars:
    PASS_VNC: "sua_senha_vnc_aqui"  # Substitua "sua_senha_vnc_aqui" pela senha VNC desejada

  tasks:
    - name: Codificar a senha VNC em base64
      set_fact:
        VNCPASS64: "{{ PASS_VNC | b64encode }}"

# Baixa e copia o applet "weather@mockturtl" na pasta correta (Projeto abandonado)
# Ao baixar o applet pela interface gráfica fica em português, mas se pegar essa pasta em português e colocar ela em "/usr/share/cinnamon/applets" (local onde ficam os applets nativos do cinnamon)
# ele volta a ficar em inglês
# wget -P /usr/share/cinnamon/applets https://cinnamon-spices.linuxmint.com/files/applets/weather@mockturtl.zip && unzip /usr/share/cinnamon/applets/weather@mockturtl.zip -d /usr/share/cinnamon/applets/
# rm -rf weather@mockturtl.zip
- name: Baixar e extrair applet de clima para Cinnamon
  tasks:
    - name: Baixar o arquivo zip do applet
      get_url:
        url: https://cinnamon-spices.linuxmint.com/files/applets/weather@mockturtl.zip
        dest: /usr/share/cinnamon/applets/weather@mockturtl.zip

    - name: Extrair o arquivo zip
      unarchive:
        src: /usr/share/cinnamon/applets/weather@mockturtl.zip
        dest: /usr/share/cinnamon/applets/

    - name: Remover o arquivo zip após extração
      file:
        path: /usr/share/cinnamon/applets/weather@mockturtl.zip
        state: absent

# Configurações em si. Cuidado com os escapes de "
- name: Configurar o arquivo de configuração do dconf para o Nemo
  tasks:
    - name: Adicionar configurações ao arquivo de configuração do dconf
      lineinfile:
        path: /etc/dconf/db/local.d/10-nemo
        line: |
          [org/nemo/window-state]
          start-with-sidebar=true
          start-with-toolbar=true
          start-with-status-bar=true
      create: yes
      state: present


# Configurações de acesso remoto
- name: Configurar configurações de acesso remoto e do ambiente de desktop
  vars:
    VNCPASS64: "sua_senha_vnc_em_base64_aqui"  # Substitua "sua_senha_vnc_em_base64_aqui" pela senha VNC codificada em base64

  tasks:
    - name: Adicionar configurações de acesso remoto ao arquivo de configuração do dconf
      lineinfile:
        path: /etc/dconf/db/local.d/01-remote-access
        line: |
          [org/gnome/desktop/remote-access]
          icon-visibility='client'
          authentication-methods=['vnc']
          enabled=true
          vnc-password='{{ VNCPASS64 }}'
      create: yes
      state: present

    - name: Adicionar configurações do screensaver ao arquivo de configuração do dconf
      lineinfile:
        path: /etc/dconf/db/local.d/02-screensaver
        line: |
          [org/cinnamon/desktop/screensaver]
          use-custom-format=true
          date-format='%a %e %b, %H:%M'
      create: yes
      state: present

    - name: Adicionar configurações da interface ao arquivo de configuração do dconf
      lineinfile:
        path: /etc/dconf/db/local.d/03-interface
        line: |
          [org/cinnamon/desktop/interface]
          clock-show-date=true
      create: yes
      state: present

    - name: Adicionar configurações do perfil do terminal ao arquivo de configuração do dconf
      lineinfile:
        path: /etc/dconf/db/local.d/04-terminal-profile
        line: |
          [org/gnome/terminal/legacy/profiles:/]
          default='default'
          list=['default']
          
          [org/gnome/terminal/legacy/profiles:/default]
          background-color='#FFFFFFFFDDDD'
          palette='#2E2E34343636:#CCCC00000000:#4E4E9A9A0606:#C4C4A0A00000:#34346565A4A4:#757550507B7B:#060698209A9A:#D3D3D7D7CFCF:#555557575353:#EFEF29292929:#8A8AE2E23434:#FCFCE9E94F4F:#72729F9FCFCF:#ADAD7F7FA8A8:#3434E2E2E2E2:#EEEEEEEEECEC'


# Updates não devem ser visíveis
# ???

# Desabilita linha de comando
# ???

# Numlock ativado
# ???

# Terminal de root
# ???

# Abrir no terminal
# ???

# Sons do Sistema
# ???

# Lixeira no desktop
# ???

# Atalhos do menu
# ???

# Tema Dark
# ???

# Background padrão
# ???

# 'Impressora Adicionada' aparece a todo momento, ainda não foi resolvido
# ???

# Desabilita notificação de rede On/Off
# ???

# Num de desktops em 1 por padrão no Gnome
# ???

# Applet de calendario
# ???

# Trava as configs do Vino
# ???

# Copia o script necessario para iniciar o terminal como root
# ???

# Finalmente, atualiza dconf
# ???