---
- name: "Cria os diretórios de configuração"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: "0755"
  loop:
    - /etc/dconf/profile
    - /etc/dconf/db/local.d/locks

# Seta o local do arquivo de config (local, ou seja, ficará em /db/local.d)
- name: "Cria o arquivo de configuração /etc/dconf/profile/user"
  ansible.builtin.copy:
    content: |
      user-db:user
      system-db:local
    dest: /etc/dconf/profile/user
    owner: root
    group: root
    mode: "0644"

- name: Criar o arquivo de configuração dconf
  ansible.builtin.template:
    src: dconf-cmc-config.j2
    dest: /etc/dconf/db/local.d/01-cmc
    owner: root
    group: root
    mode: "0644"

- name: "Configurar o applet de calendário"
  block:
    - name: Lê configuração do applet em formato JSON
      ansible.builtin.slurp:
        src: "{{ estacao_caljson }}"
      register: caljson

    # - name: Exibe conteúdo do json
    #   ansible.builtin.debug:
    #     msg: "{{ caljson['content'] | b64decode }}"

    - name: "Set 'use-custom-format' to true"
      ansible.builtin.set_fact:
        json_content: "{{ caljson['content'] | b64decode | from_json | combine({'use-custom-format': {'value': true}}) }}"

    - name: "Set custom format value"
      ansible.builtin.set_fact:
        json_content: "{{ json_content | combine({'custom-format': {'value': '%A, %e %B %Y, %H:%M'}}) }}"

    - name: "Write updated JSON back to file"
      ansible.builtin.copy:
        content: "{{ json_content | to_nice_json }}"
        dest: "{{ estacao_caljson }}"
        mode: "0644"
        backup: true

- name: "Trava as configs do Vino"
  ansible.builtin.copy:
    content: |
      /org/gnome/desktop/remote-access/icon-visibility
      /org/gnome/desktop/remote-access/authentication-methods
      /org/gnome/desktop/remote-access/enabled
      /org/gnome/desktop/remote-access/vnc-password
    dest: /etc/dconf/db/local.d/locks/01-cmc
    mode: "0644"

- name: "Copia  o script necessario para iniciar o terminal como root"
  ansible.builtin.copy:
    src: "root-terminal.sh"
    dest: "{{ estacao_cmc_scripts_dir }}/root-terminal.sh"
    mode: "0755"

- name: "Atualiza dconf"
  ansible.builtin.command: dconf update
