# 130-login-manual

# Desabilita login como guest
# ???

# Habilita login manual e esconde usuários
# ???

# Muda background do greeter
# Greeter com G maiúsculo pq tem bug marcado como resolvido... Mas não resolvido
# ???