---
- name: Configura script de boot
  ansible.builtin.template:
    src: cmc-boot.sh.j2
    dest: "{{ estacao_bootsh }}"
    owner: root
    group: root
    mode: "0755"

- name: Configura cmc-boot.service
  ansible.builtin.template:
    src: cmc-boot.service.j2
    dest: "{{ estacao_servico_boot }}"
    owner: root
    group: root
    mode: "0644"

- name: Configura cmc-boot.timer
  ansible.builtin.copy:
    src: cmc-boot.timer
    dest: "{{ estacao_servico_boot_timer }}"
    owner: root
    group: root
    mode: "0644"

- name: Habilita o serviço e roda o script imediatamente
  ansible.builtin.service:
    name: cmc-boot.service
    enabled: true
    state: started

- name: Habilita o timer
  ansible.builtin.service:
    name: cmc-boot.timer
    enabled: true
    state: started
