---
- name: Seta hostname
  ansible.builtin.command:
    cmd: "{{ estacao_bootsh }}"

- name: Verifica hostname
  ansible.builtin.command:
    cmd: hostname -f
  register: hostname
  changed_when: false

- name: Garante que hostname esteja configurado
  ansible.builtin.assert:
    that: (estacao_ad_domain | lower) in hostname.stdout
    fail_msg: "Hostname não configurado, abortando"

- name: "Instala SSSD, REALM, KERBEROS e ADCLI"
  ansible.builtin.apt:
    name:
      - sssd
      - sssd-ad
      - sssd-tools
      - realmd
      - krb5-user
      - samba-common
      - packagekit
      - adcli
    state: present

- name: Pega AD Domain Controllers
  ansible.builtin.shell:
    cmd: adcli info cmc.local | grep domain-controllers | cut -d"=" -f2 | xargs | sed 's/ /, /g'
  register: ad_domain_controllers_list

- name: Seta lista  
  ansible.builtin.set_fact:
    ad_domain_controllers: "{{ad_domain_controllers_list.stdout | lower}}"

- name: Configuração do Kerberos
  ansible.builtin.template:
    src: templates/krb5-conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Verifica se a máquina já está no realm
  ansible.builtin.shell:
    cmd: realm list | grep -iq "{{ estacao_ad_domain }}"
  register: ad_domain_list
  ignore_errors: true
  changed_when: false

- name: Adiciona o computador ao domínio caso não esteja
  ansible.builtin.shell:
    cmd: echo "{{ estacao_ad_join_pass }}" | realm join -U "{{ estacao_ad_join_user }}" "{{ estacao_ad_domain | lower }}"
  when: ad_domain_list.rc != 0

- name: Configuração do sssd
  ansible.builtin.template:
    src: templates/sssd-conf.j2
    dest: /etc/sssd/conf.d/01-cmc.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart SSSD

- name: Cria diretorio sssd.service.d se nao existir
  ansible.builtin.shell:
    cmd: test ! -d /etc/systemd/system/sssd.service.d && mkdir /etc/systemd/system/sssd.service.d
  ignore_errors: true
  tags: testanetconf

- name: Cria network.conf
  ansible.builtin.template:
    src: templates/network.conf.j2
    dest: /etc/systemd/system/sssd.service.d/network.conf
  tags: testanetconf

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
