# 150-bashrc

- name: Configurar aliases e funções locais
  become: yes

  tasks:
    - name: Comentar aliases existentes no .bashrc
      lineinfile:
        path: /root/.bashrc
        regex: '^(alias ll|alias la|alias l)'
        line: '#\g<0>'
      backup: yes

    - name: Criar arquivo .bash_aliases com os novos aliases e funções
      copy:
        content: |
          # Aliases e funcoes locais
          alias ll='ls -lh'
          alias la='ls -a'
          alias l='ls'
          alias mv='mv -iv'
          alias cp='cp -iv'
          alias rm='rm -iv'

          # Faz backup local
          function bkp() {
              if [ -z "$1" ]; then
                  echo "Uso: bkp [arquivo]";
              else
                  mkdir -p ./bkp
                  'cp' -Lv --preserve=all "$1" "./bkp/$1-$(date +%F-%H-%M-%S)"
              fi
          }
        dest: /root/.bash_aliases
      backup: yes

    - name: Copiar o arquivo .bash_aliases para o diretório /etc/skel
      copy:
        src: /root/.bash_aliases
        dest: /etc/skel/.bash_aliases

    - name: Definir permissões do arquivo /etc/skel/.bash_aliases
      file:
        path: /etc/skel/.bash_aliases
        owner: root
        group: root
        mode: "0644"


