---
- name: "Substitui linha 'hosts:.*'' e cria um backup"
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts:\t\tfiles dns"
    backup: true

- name: Automatiza a criação do diretório HOME após o login
  ansible.builtin.command:
    cmd: pam-auth-update --force --enable mkhomedir
