# 150-bashrc

- name: Comenta linhas de alias do /root/.bashrc
  ansible.builtin.replace:
    path: /root/.bashrc
    regexp: "^(alias l[al]?.*)$"
    replace: '#\1'

- name: Configura /root/.bash_aliases
  ansible.builtin.copy:
    dest: "{{ item }}"
    content: |
      # Aliases e funcoes locais
      alias ll='ls -lh'
      alias la='ls -a'
      alias l='ls'
      alias mv='mv -iv'
      alias cp='cp -iv'
      alias rm='rm -iv'

      # Faz backup local
      function bkp() {
        if [ -z \"\$1\" ]; then
          echo \"Uso: bkp [arquivo]\";
        else
          mkdir -p ./bkp
          'cp' -Lv --preserve=all \"\$1\" \"./bkp/\$1-\$(date +%F-%H-%M-%S)\"
        fi
      }
    mode: "0644"
  with_items:
    - /root/.bash_aliases
    - /etc/skel/.bash_aliases
