# 160-nscd-cache

################################################################################
# Tradutor script ansible: Gabriel Lisboa Conegero
# Autora script shell: Renata Carvalho
# Data: 28/11/17
# Versão: 1.0
# Descrição: Esse script modifica as configurações do NSCD para que este guarde
# o cache corretamente e funcione offline, impedindo o linux mint de travar
# quando a rede cair. Está configurado para guardar o cache por 64.800
# segundos, ou 18 horas.
################################################################################

- name: "Verifica se arquivos de configuração existem : ({{ task_name }})"
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items:
    - /etc/nsswitch.conf
    - /etc/nscd.conf
  register: files_to_check

- name: "Configura NSCD : ({{ task_name }})"
  when: (files_to_check.results | map(attribute="stat.exists")) is all
  block:
    - name: "Configura NSCD : ({{ task_name }})"
      ansible.builtin.copy:
        dest: /etc/nscd.conf
        backup: true
        mode: "0644"
        src: "nscd.conf"
    - name: "Configura NSSWITCH : ({{ task_name }})"
      ansible.builtin.copy:
        dest: /etc/nsswitch.conf
        backup: true
        mode: "0644"
        src: "nsswitch.conf"
