---
- name: "Substitui linha 'hosts:.*'' e cria um backup: ({{ task_name }})"
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^hosts:.*$"
    line: 'hosts:\t\tfiles dns'
    backrefs: true
    backup: true

- name: "Automatiza a criação do diretório HOME após o login: ({{ task_name }})"
  ansible.builtin.command:
    cmd: pam-auth-update --force --enable mkhomedir
  register: pam_update

