---
################################################################################
# Tradutor script ansible: Gabriel Lisboa Conegero
# Autora script shell: Renata Carvalho
# Data: 08/12/17
# Versão: 1.0
# Descrição: Esse script modifica as configurações do PAM para que este guarde
# o cache dos users corretamente e permita o login offline, permitindo o uso
# dos programas locais.
################################################################################

- name: "Verifica se arquivos de configuração existem : ({{ task_name }})"
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items:
    - /etc/pam.d/common-auth
    - /etc/pam.d/common-account
  register: files_to_check

- name: "Configura arquivos : ({{ task_name }})"
  when: (files_to_check.results | map(attribute="stat.exists")) is all
  block:
    - name: "(180-pam-login-offline.yml) Instalação dos pacotes necessarios : ({{ task_name }})"
      ansible.builtin.apt:
        name:
          - libnss-ldapd
          - nss-updatedb
          - libnss-db
          - libpam-ccreds
        state: present

    - name: "Configura /etc/pam.d/ : ({{ task_name }})"
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
        backup: true
        mode: "0644"
      with_items:
        - dest: "/etc/pam.d/common-auth"
          src: "t-180/common-auth"
        - dest: "/etc/pam.d/common-account"
          src: "t-180/common-account"
        - dest: "/etc/pam.d/common-session"
          src: "t-180/common-session"

    - name: "Config final do arquivo nsswitch : ({{ task_name }})"
      ansible.builtin.replace:
        backup: true
        path: /etc/nsswitch.conf
        regexp: "^(passwd:|group:).*$"
        replace: '\1 compat files ldap [NOTFOUND=return] db'
