---
- name: "Comenta linhas de alias do /root/.bashrc : ({{ task_name }})"
  ansible.builtin.replace:
    path: /root/.bashrc
    regexp: "^(alias l[al]?.*)$"
    replace: '#\1'

- name: "Configura /root/.bash_aliases : ({{ task_name }})"
  ansible.builtin.copy:
    dest: "{{ item }}"
    src: "bash_aliases"
    mode: "0644"
  loop:
    - /root/.bash_aliases
    - /etc/skel/.bash_aliases
