---
- name: "Verifica se /etc/fstab existe : ({{ task_name }})"
  ansible.builtin.stat:
    path: /etc/fstab
  register: fstab_file

- name: "Montando NFS : ({{ task_name }})"
  when: fstab_file.stat.exists
  block:
    - name: "Cria diretório de montagem : ({{ task_name }})"
      ansible.builtin.file:
        path: /mnt/suporte
        state: directory
        mode: "0755"

    - name: "Configura /etc/fstab : ({{ task_name }})"
      ansible.posix.mount:
        path: "{{ estacao_mnt_suporte }}"
        src: "{{ estacao_nfs_serv }}"
        fstype: "nfs"
        opts: "timeo=5,retrans=3,retry=10,ro,fg,intr,_netdev,soft,nofail"
        dump: 0
        passno: 0
        backup: true
        state: present
