---
- name: "Configura SSH : ({{ task_name }})"
  ansible.builtin.include_tasks: aux/ssh-config.yml
  with_items:
    - msg: Desabilitando login SSH para root
      config:
        name: "PermitRootLogin"
        value: "no"
    - msg: Restringindo SSH apenas para usuários da DTIC
      config:
        name: "AllowGroups"
        value: "dtic"
