---
- name: "Cria arquivo e configura vino-server"
  ansible.builtin.copy:
    dest: "{{ estacao_vino }}"
    src: "vino-server.desktop"
    owner: root
    group: root
    mode: "0644"

- name: "Atualiza o launcher do vino-server para que inicie automaticamente"
  ansible.builtin.lineinfile:
    path: "{{ estacao_vino }}"
    regexp: "^X-GNOME-Autostart-enabled"
    line: "X-GNOME-Autostart-enabled=true"
