---
- name: "Pega informações sobre vino-server : ({{ task_name }})"
  ansible.builtin.stat:
    path: "{{ estacao_vino }}"
  register: vino_info

- name: "Cria arquivo e configura vino-server : ({{ task_name }})"
  when: not vino_info.stat.exists
  ansible.builtin.copy:
    dest: "{{ estacao_vino }}"
    src: "vino-server.desktop"
    mode: "0644"

- name: "Atualiza o launcher do vino-server para que inicie automaticamente : ({{ task_name }})"
  ansible.builtin.lineinfile:
    path: "{{ estacao_vino }}"
    regexp: '^X-GNOME-Autostart-enabled'
    line: "X-GNOME-Autostart-enabled=true"
