---
- name: "Renomeia os itens de /usr/share/applications para .disable"
  ansible.builtin.command:
    cmd: "mv {{ item }} {{ item }}.disable"
    creates: "{{ item }}.disable"
    removes: "{{ item }}"
  loop:
    # - /usr/share/applications/nm-connection-editor.desktop
    - /usr/share/applications/mintupdate.desktop
    - /usr/share/applications/mintreport.desktop
    - /usr/share/applications/lightdm-settings.desktop
    - /usr/share/applications/mintwelcome.desktop
