---
# Insere yes nas tags allow_any, allow_inactive e allow_active 
# dentro das tags action de id fylesystem-mount, filesystem-unmount-others
# e filesystem-mount-system no arquivo de permissões do Udisks2
# para autenticação automática do usuário. Mais informações em:
# https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

- name: "Define permissões para dispositivos externos"
  community.general.xml:
    path: /usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy
    xpath: "//policyconfig/action[@id='org.freedesktop.udisks2.{{ item[0] }}']/defaults/{{ item[1] }}"
    value: "yes"
  loop: "{{ file_system_actions | product(default_acls) | list }}"
  vars:
    file_system_actions:
      - filesystem-mount
      - filesystem-unmount-others
      - filesystem-mount-system
    default_acls:
      - allow_any
      - allow_inactive
      - allow_active
