---
- name: "Assegura permissão de dispositivos bluetooth : ({{ task_name }})"
  community.general.xml:
    path: /usr/share/polkit-1/actions/org.blueman.policy
    xpath: "//policyconfig/action[@id='org.blueman.{{ item[0] }}']/defaults/{{ item[1] }}"
    value: 'yes'
  loop: "{{ file_system_actions | product(default_acls) | list }}"
  register: xml_edit
  vars:
    file_system_actions:
      - network.setup
      - rfkill.setstate
    default_acls:
      - allow_inactive
      - allow_active
