---
- name: "Remove execução dos programas default : ({{ task_name }})"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0700"
  with_items:
    - /usr/bin/gnome-terminal
    - /usr/bin/mintupdate
    - /usr/bin/mintreport
    - /usr/bin/cinnamon-menu-editor
    - /usr/bin/cinnamon-desktop-editor
    # - /usr/bin/nm-connection-editor
    # - /usr/bin/nm-applet
    # - /usr/bin/gnome-keyring
    # - /usr/bin/gnome-keyring-3
    # - /usr/bin/gnome-keyring-daemon
  tags:
    - molecule-notest

- name: "Cria uma ACL para ajustar as permissões do usuário suporte: ({{ task_name }})"
  ansible.posix.acl:
    path: "{{ item.path }}"
    entity: suporte
    etype: user
    state: present
    permissions: "{{ item.permissions | default('rx') }}"
  loop:
    - path: /usr/bin/gnome-terminal
      permissions: "rwx"
    - path: /usr/bin/cinnamon-desktop-editor
    # - path: /usr/bin/nm-connection-editor
    # - path: /usr/bin/nm-applet

- name: "Cria uma ACL para ajustar as permissões da DTIC : ({{ task_name }})"
  ansible.posix.acl:
    path: "{{ item.path }}"
    entity: "{{ estacao_dtic_group }}"
    etype: group
    state: present
    permissions: "{{ item.permissions | default('rx') }}"
  loop:
    - path: /usr/bin/gnome-terminal
    - path: /usr/bin/cinnamon-desktop-editor
    # - path: /usr/bin/nm-connection-editor
    # - path: /usr/bin/nm-applet
