---

# Altera tempo de retencao do syslog, auth, messages e outros para 6 meses

- name: Mantém logs por 27 semanas (~6 meses)
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: 'rotate\s+\d+'
    replace: "rotate 27"
  loop:
    - /etc/logrotate.d/rsyslog
    - /etc/logrotate.d/sssd-common

- name: Rotaciona logs diariamente
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: "daily"
    replace: "weekly"
  loop:
    - /etc/logrotate.d/rsyslog
    - /etc/logrotate.d/sssd-common

# Desabilita IPV6 method para evitar inundação de logs

- name: Descobre nome da conexão
  ansible.builtin.shell: nmcli -t -f NAME connection show | head -n 1
  register: conn_name

- name: Desabilita IPV6 method
  community.general.nmcli:
    type: ethernet
    conn_name: "{{ conn_name.stdout }}"
    method6: "disabled"
    state: present

- name: Reinicia NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
