---
- name: "Copia arquivo zoom-updater para seu respectivo diretorio"
  block:
    - name: "Copy zoom-update.sh"
      ansible.builtin.copy:
        src: "zoom-update.sh"
        dest: "/usr/local/cmc/scripts/zoom-update.sh"
        mode: "0755"

- name: "Instala serviço no systemd"
  block:
    - name: "Copy zoom-update.service"
      ansible.builtin.copy:
        src: "zoom-update.service"
        dest: "/etc/systemd/system/zoom-update.service"
        owner: root
        group: root
        mode: "0644"

- name: "Cria timer de serviço no systemd"
  block:
    - name: "Copia zoom-update.timer"
      ansible.builtin.copy:
        src: "zoom-update.timer"
        dest: "/etc/systemd/system/zoom-update.timer"
        owner: root
        group: root
        mode: "0644"

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Enable e start em zoom-update.service"
  ansible.builtin.service:
    name: "zoom-update.service"
    enabled: true
    state: started

- name: "Enable em zoom-update.timer"
  ansible.builtin.service:
    name: "zoom-update.timer"
    enabled: true
