---
- name: Instala script de atualização do zoom
  ansible.builtin.template:
    src: zoom-update.sh.j2
    dest: "{{ estacao_zoomsh }}"
    owner: root
    group: root
    mode: "0755"

- name: Instala serviço de atualização do zoom
  ansible.builtin.template:
    src: zoom-update.service.j2
    dest: "{{ estacao_servico_zoom_update }}"
    owner: root
    group: root
    mode: "0644"

- name: Cria timer de atualização do zoom
  ansible.builtin.copy:
    src: zoom-update.timer
    dest: "{{ estacao_servico_zoom_timer }}"
    owner: root
    group: root
    mode: "0644"

- name: Habilita o serviço
  ansible.builtin.service:
    name: zoom-update.service
    enabled: true
    state: started

- name: Habilita o timer
  ansible.builtin.service:
    name: zoom-update.timer
    enabled: true
