---
# Esquema de versionamento SemVer: https://semver.org/
# Formato: ET-MAJOR.MINOR.PATCH
- name: "Mantém versionamento"
  ansible.builtin.copy:
    dest: "{{ estacao_cmc_dir }}/version"
    content: "ET-6.2.0"
    mode: "0644"
