---
- name: Cria diretório /usr/local/cmc
  ansible.builtin.file:
    path: "/usr/local/cmc"
    state: directory
    mode: "0755"

- name: Task-010
  ansible.builtin.import_tasks: 010-user-group-suporte.yml
  tags:
    - t-010

- name: Task-020
  ansible.builtin.import_tasks: 020-remover-programas.yml
  tags:
    - t-020

- name: Task-030
  ansible.builtin.import_tasks: 030-instala-programas.yml
  tags:
    - t-030

- name: Task-040
  ansible.builtin.import_tasks: 040-imagens-cmc.yml
  tags:
    - t-040

- name: Task-050
  ansible.builtin.import_tasks: 050-skel.yml
  tags:
    - t-050

- name: Task-060
  ansible.builtin.import_tasks: 060-configura-browsers.yml
  tags:
    - t-060

- name: Task-070
  ansible.builtin.import_tasks: 070-autostart.yml
  tags:
    - t-070

- name: Task-080
  ansible.builtin.import_tasks: 080-politica-informatica.yml
  tags:
    - t-080

- name: Task-090
  ansible.builtin.import_tasks: 090-desabilita-tty.yml
  tags:
    - t-090

- name: Task-100
  ansible.builtin.import_tasks: 100-dconf.yml
  tags:
    - t-100

- name: Task-110
  ansible.builtin.import_tasks: 110-terminal-policy.yml
  tags:
    - t-110

- name: Task-120
  ansible.builtin.import_tasks: 120-ntp-server.yml
  tags:
    - t-120

- name: Task-130
  ansible.builtin.import_tasks: 130-configura-dns.yml
  tags:
    - t-130

- name: Task-135
  ansible.builtin.import_tasks: 135-script-boot.yml
  tags:
    - t-135

- name: Task-140
  ansible.builtin.import_tasks: 140-integra-ad.yml
  tags:
    - t-140

- name: Task-150
  ansible.builtin.import_tasks: 150-configura-pam.yml
  tags:
    - t-150

- name: Task-160
  ansible.builtin.import_tasks: 160-sudoers.yml
  tags:
    - t-160

- name: Task-170
  ansible.builtin.import_tasks: 170-unattended-upgrades.yml
  tags:
    - t-170

- name: Task-180
  ansible.builtin.import_tasks: 180-bashrc.yml
  tags:
    - t-180

- name: Task-190
  ansible.builtin.import_tasks: 190-nfs-mount.yml
  tags:
    - t-190

- name: Task-200
  ansible.builtin.import_tasks: 200-script-rede.yml
  tags:
    - t-200

- name: Task-210
  ansible.builtin.import_tasks: 210-ssh-server.yml
  tags:
    - t-210

- name: Task-220
  ansible.builtin.import_tasks: 220-vnc.yml
  tags:
    - t-220

- name: Task-230
  ansible.builtin.import_tasks: 230-menu-items.yml
  tags:
    - t-230

- name: Task-240
  ansible.builtin.import_tasks: 240-login-grafico.yml
  tags:
    - t-240

- name: Task-250
  ansible.builtin.import_tasks: 250-configura-cups.yml
  tags:
    - t-250

- name: Task-260
  ansible.builtin.import_tasks: 260-mount-pendrive.yml
  tags:
    - t-260

- name: Task-270
  ansible.builtin.import_tasks: 270-bloqueio-cinnamon.yml
  tags:
    - t-270

- name: Task-280
  ansible.builtin.import_tasks: 280-on-login.yml
  tags:
    - t-280

- name: Task-290
  ansible.builtin.import_tasks: 290-configura-logs.yml
  tags:
    - t-290

- name: Task-300
  ansible.builtin.import_tasks: 300-zoom-autoupdate.yml
  tags:
    - t-300

- name: Task-990
  ansible.builtin.import_tasks: 990-versionamento.yml
  tags:
    - t-990

- name: Task-999
  ansible.builtin.import_tasks: 999-arquivos-modificados.yml
  tags:
    - t-999
