---

- name: Tasks concluidas
  when: estacao_teste is falsy
  become: true
  block:
    - name: Task-010
      ansible.builtin.import_tasks: 010-user-group-suporte.yml

    - name: Task-020
      ansible.builtin.import_tasks: 020-remover-programas.yml

    - name: Task-030
      ansible.builtin.import_tasks: 030-instala-programas.yml

    - name: Task-035
      ansible.builtin.import_tasks: 035-imagens-cmc.yml

- name: Tasks em teste
  when: estacao_teste is truthy
  become: true
  block:
    - name: Task-040
      ansible.builtin.import_tasks: 040-skel.yml
