---

- name: Cria diretório /usr/local/cmc
  ansible.builtin.file:
    path: "/usr/local/cmc"
    state: directory
    mode: "0755"
  become: true


- name: Tasks concluidas
  when: estacao_teste is falsy
  become: true
  block:
    - name: Task-010
      ansible.builtin.import_tasks: 010-user-group-suporte.yml

    - name: Task-020
      ansible.builtin.import_tasks: 020-remover-programas.yml

    - name: Task-030
      ansible.builtin.import_tasks: 030-instala-programas.yml

    - name: Task-035
      ansible.builtin.import_tasks: 035-imagens-cmc.yml

    - name: Task-040
      ansible.builtin.import_tasks: 040-skel.yml

    - name: Task-050
      ansible.builtin.import_tasks: 050-config-browsers.yml

    - name: Task-055
      ansible.builtin.import_tasks: 055-programas-default.yml

    - name: Task-060
      ansible.builtin.import_tasks: 060-autostart.yml

    - name: Task-070
      ansible.builtin.import_tasks: 070-politica-informatica.yml

    - name: Task-080
      ansible.builtin.import_tasks: 080-desabilita-tty.yml

    - name: Task-100
      ansible.builtin.import_tasks: 100-dconf.yml

    - name: Task-105
      ansible.builtin.import_tasks: 105-terminal-policy.yml

- name: Tasks em teste
  when: estacao_teste is truthy
  become: true
  block:
    - name: Task-110
      ansible.builtin.import_tasks: 110-configura-dns.yml
