---

- name: Cria diretório /usr/local/cmc
  ansible.builtin.file:
    path: "/usr/local/cmc"
    state: directory
    mode: "0755"
  become: true

- name: Tasks concluidas
  when: estacao_teste is falsy
  become: true
  block:
    - name: Task-010
      ansible.builtin.import_tasks: 010-user-group-suporte.yml

    - name: Task-020
      ansible.builtin.import_tasks: 020-remover-programas.yml

    - name: Task-030
      ansible.builtin.import_tasks: 030-instala-programas.yml

    - name: Task-035
      ansible.builtin.import_tasks: 035-imagens-cmc.yml

    - name: Task-040
      ansible.builtin.import_tasks: 040-skel.yml

    - name: Task-050
      ansible.builtin.import_tasks: 050-config-browsers.yml

    - name: Task-055
      ansible.builtin.import_tasks: 055-programas-default.yml

    - name: Task-060
      ansible.builtin.import_tasks: 060-autostart.yml

    - name: Task-070
      ansible.builtin.import_tasks: 070-politica-informatica.yml

    - name: Task-080
      ansible.builtin.import_tasks: 080-desabilita-tty.yml

    - name: Task-100
      ansible.builtin.import_tasks: 100-dconf.yml

    - name: Task-105
      ansible.builtin.import_tasks: 105-terminal-policy.yml

    - name: Task-110
      ansible.builtin.import_tasks: 110-configura-dns.yml

    - name: Task-120
      ansible.builtin.import_tasks: 120-ldap-install.yml

    - name: Task-130
      ansible.builtin.import_tasks: 130-login-manual.yml

    - name: Task-140
      ansible.builtin.import_tasks: 140-unattended-upgrades.yml

    - name: Task-150
      ansible.builtin.import_tasks: 150-bashrc.yml

    - name: Task-160
      ansible.builtin.import_tasks: 160-nscd-cache.yml

    - name: Task-170
      ansible.builtin.import_tasks: 170-nfs-mount.yml

    - name: Task-180
      ansible.builtin.import_tasks: 180-pam-login-offline.yml

    - name: Task-190
      ansible.builtin.import_tasks: 190-pam_mount-owncloud.yml

    - name: Task-200
      ansible.builtin.import_tasks: 200-script-rede.yml

    - name: Task-210
      ansible.builtin.import_tasks: 210-ssh-server.yml

    - name: Task-220
      ansible.builtin.import_tasks: 220-vnc.yml

    - name: Task-230
      ansible.builtin.import_tasks: 230-menu-items.yml

    - name: Task-240
      ansible.builtin.import_tasks: 240-ntp-server.yml

- name: Tasks em teste
  when: estacao_teste is truthy
  become: true
  block:
    - name: Task-250
      ansible.builtin.import_tasks: 250-configura-cups.yml
