galaxy_info:
  author: "dtic-cmc"
  namespace: cmcuritiba
  description: "role para configurar estação de trabalho mint"

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.16.6

  platforms:
  - name: Ubuntu
    versions:
    - jammy

  galaxy_tags: []

dependencies: []

collections:
  - community.general
  - ansible.posix
